[package]
name = "eventsource-stream2"
version = "0.2.3"
authors = [
    "Julian Popescu <jpopesculian@gmail.com>",
    "Adam Stopher <adam.stopher@protonmail.com>",
]
edition = "2018"
resolver = "2"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/SneedSeedFeed/eventsource-stream"
documentation = "https://docs.rs/eventsource-stream2/"
repository = "https://github.com/SneedSeedFeed/eventsource-stream"
description = "A basic building block for building an Eventsource from a Stream of bytes, and updated fork of eventsource-stream."
keywords = ["sse", "eventsource", "stream", "parse", "event"]
categories = [
    "web-programming::http-client",
    "no-std",
    "parsing",
    "asynchronous",
]

[features]
default = ["std"]
std = ["futures-core/std", "memchr/std", "memchr/use_std"]

[dependencies]
futures-core = { version = "0.3.32", default-features = false }
memchr = { version = "2.8.1", default-features = false }
pin-project-lite = "0.2.17"

[dev-dependencies]
futures = "0.3.32"
http = "1.4.1"
reqwest = { version = "0.13.4", features = ["stream"] }
tokio = { version = "1.52", features = ["macros", "rt"] }
url = "2.5"
